### ISSUE TITLE
Cant save filled form, endless request

### ISSUE THREAD

**Issue by bios90** [mikehaertl/php-pdftk#156] opened 2019-05-16 12:03 UTC
I am using php-pdftk on my local machine - Macbook.

Pdftk installed, all directories have 777 permissions.

I use thi code to fill form

```
        $pdf = new Pdf('/Applications/XAMPP/xamppfiles/htdocs/eikeihr/public/tfchb.pdf'
, ['command' => '/usr/local/bin/pdftk','useExec' => true,]);

        $pdf->fillForm([
            'tf1' => 'Test Form 1',
            'tf2' => 'Test Form 2',
        ])
            ->needAppearances()
            ->saveAs('/Applications/XAMPP/xamppfiles/htdocs/eikeihr/public/filled.pdf');
```

All code before ->saveAs line works normal, but calling saveAs causes endless request with no errors.

Can i fix it somehow?

**Comment by mikehaertl** [comment] 2019-05-16 12:06
Endless requests can usually only be caused by sending `Location: ...` HTTP headers. Our library doesn't do that. You should find out, what causes these redirect, e.g. with `curl -I http://yourdomain.com/your-scrip.php` or by using the network tab in your browsers dev tools.

**Comment by bios90** [comment] 2019-05-16 12:38
Thanks for answer but if i use this code

```
        $pdf->fillForm([
            'tf1' => 'fsdf',
            'tf2' => 'fiesafasld2',
        ])
            ->needAppearances();//Without Saving

        return "success";
```
I get "success" message, but if i use this

```
        $pdf = new Pdf('/Applications/XAMPP/xamppfiles/htdocs/eikeihr/public/tfchb.pdf'
, ['command' => '/usr/local/bin/pdftk','useExec' => true,]);

        $pdf->fillForm([
            'tf1' => 'Test Form 1',
            'tf2' => 'Test Form 2',
        ])
            ->needAppearances()
            ->saveAs('/Applications/XAMPP/xamppfiles/htdocs/eikeihr/public/filled.pdf');//Tryuing to save
         return "success"
```

I do not get any response.

**Comment by mikehaertl** [comment] 2019-05-16 12:54
I already gave you some hints, how you can debug your setup. And explained that our library does not cause this. It must have to do with your setup, not our library.

I'm closing this. If you think something is broken please provide a clear example to reproduce the issue (your example is the standard use case and works for me).

**Closed by mikehaertl** 2019-05-16 12:54 UTC
