### ISSUE TITLE
Incorrect display of the small c with caron letter

### ISSUE THREAD

**Issue by ilabcrossmedia** [mikehaertl/php-pdftk#12] opened 2015-02-12 10:33 UTC
Hi,

I've noticed that when creating a fdf file the 'č' letter does not get properly displayed - all other utf-8 characters are displayed fine. 
So I've checked the output byte by byte and noticed, that the letter 'č' is represented as chr(0x01).chr(0x5c).chr(0x72) in an adobe created fdf file - so this seems to be some irregularity.
So I modified the FdfFile class to respect that behaviour - and the problem is solved for me.

    $utf16Value = strtr($utf16Value, array('(' => '\\(', ')'=>'\\)', chr(0x01).chr(0x0d) => chr(0x01).chr(0x5c).chr(0x72)));
 
has anyone else experienced this behaviour?

**Comment by mikehaertl** [comment] 2015-02-12 10:57
This is a duplicate of #4.

**Closed by mikehaertl** 2015-02-12 10:57 UTC
