### ISSUE TITLE
PDF form field name is like an array

### ISSUE THREAD

**Issue by shafrazlk** [mikehaertl/php-pdftk#46] opened 2016-04-04 14:41 UTC
Hi,

I have a PDF file with a form, that the field names in the form are like FirstName[0], LastName[0] and etc. I am unable to fill this type of form with the package.

Please advice me if there is any solution to this.

**Comment by mikehaertl** [comment] 2016-04-04 17:55
That's probably a duplicate of #29. Right now there's no support for this, sorry.

**Closed by mikehaertl** 2016-04-04 17:55 UTC
