### ISSUE TITLE
Output PDF file permissions are inaccessible to PHP

### ISSUE THREAD

**Issue by jdillman1989** [mikehaertl/php-pdftk#111] opened 2018-03-04 16:58 UTC
```
	$pdf = new Pdf('./pdf-forms/raw/new_mexico.pdf');
	$pdf->fillForm($data)
	    ->needAppearances()
	    ->saveAs('./pdf-forms/flat/new_mexico-flat.pdf');
```
The output file new_mexico-flat.pdf is getting permissions 0644 making it inaccessible to PHP.

`-rw-r--r-- 1 www-data www-data 324399 Mar 4 01:12 new_mexico-flat.pdf`

I have a process that needs to attach the output PDF to an email, but it's giving me an error:

`PHPMailer class returned an error message: Could not access file`

Is there a way to control the permissions of the output file so that it is accessible to PHP? Is there a way to change the user/permission level that runs PDFtk?

**Comment by mikehaertl** [comment] 2018-03-04 18:48
This sounds very unreasonable. The file is written by PHP itself. So if PHP can't read it back afterwards, something else must be going on. See here:

https://github.com/mikehaertl/php-pdftk/blob/master/src/Pdf.php#L498

I don't think that I can help you in any way. It must be something else, why you can't read that file.

**Comment by mikehaertl** [comment] 2018-03-04 18:51
And one more note: `644` does not mean at all, that PHP has no read permission. In fact, it's `-rw-r--r--`. The last triplet indicates read permission for everyone. I'm closing this as I can't see how the problem could be caused by this library.

**Closed by mikehaertl** 2018-03-04 18:51 UTC
