### ISSUE TITLE
How do you fill out checkboxes and radio buttons?

### ISSUE THREAD

**Issue by cosmomathieu** [mikehaertl/php-pdftk#110] opened 2018-02-26 17:17 UTC
I've followed the examples on how to fill out text fields and text boxes, and those work great. However, I can't set the value of a radio button. Is there a different syntax that should be used for a radio button?

**Comment by mikehaertl** [comment] 2018-02-26 17:30
No, it's the same. Maybe try to inspect your form with `pdftk xyz.pdf dump_data_fields` first. Here's an example from one of my PDFs:

```
FieldType: Button
FieldName: invoice
FieldFlags: 0
FieldJustification: Left
FieldStateOption: 1
FieldStateOption: 2
FieldStateOption: Off
```

Here the field name is `invoice` and the valid values are `1` and `2`. That's what I use in my code and  this works.

As this is not a bug report I'm closing this. Please understand that I can't provide more help or private support.

**Closed by mikehaertl** 2018-02-26 17:30 UTC

**Comment by cosmomathieu** [comment] 2018-02-26 17:38
Thank you for your quick response. It turns out that my form had four field state options: 

```
---
FieldType: Button
FieldName: form1[0].InitialInspection_1[0].Body[0].probeType[0]
FieldFlags: 49152
FieldValue: 1
FieldJustification: Left
FieldStateOption: 0
FieldStateOption: 1
FieldStateOption: 2
FieldStateOption: Off
```

I was simply checking for `0` and `1`. While `2` was the one that set the correct state for the radio button. 

Thanks again!

**Comment by mharoot** [comment] 2018-08-15 18:16
```
---
FieldType: Button
FieldName: s1d4
FieldNameAlt: Check if april
FieldFlags: 262144
FieldValue: Off
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: s1d4
---
```

how do you set this?

```php
$fields = array(
  's1d4' => 'Yes',
  's1d5' => 'On',
  's1d6' => 1,
  's1d7' => true,
  's1d8' => 0,
  's1d9' => 2,
  's1d10' => 4,
);

require __DIR__ . '/vendor/autoload.php';
use mikehaertl\pdftk\Pdf; 
// Fill form with data array
    $pdf = new Pdf('form.pdf');
    $pdf->fillForm($fields)
        ->needAppearances()
        ->saveAs('filled.pdf');
```

**Comment by saqaw** [comment] 2019-06-09 14:15
what i am doing wrong,please guide me.
My pdf fields
> 
FieldType: Button
FieldName: aaaa
FieldFlags: 0
FieldValue: Off
FieldJustification: Left
FieldStateOption: Off
FieldStateOption: Yes
> 
here is my code

``ob_start();
    require('fpdf.php');
    $pdf = new FPDF();
require('fpdm.php');

$fields = array(
	'POPMLSAddress'    => $_POST['Text3'],
	'POPMLSCity' => ' ',
	'POPMLSFullPostal'=> ' ',
	
	//'Temp111'    => $_POST['Text4'],
	//'Temp222'    => $_POST['Text5'], 

	'FLOBuyerName1'    => $_POST['Text6'],
	'FLOBuyerName2'=> ' ',
				
	'buyer_brokerage'    => $_POST['Text7'],
	'offer_date'    => $_POST['Text8'],
	'offered_price'    => $_POST['Text9'],
	'amount_1'    => $_POST['Text10'],
	'amount_2'    => $_POST['Text11'],
	'amount_3'    => $_POST['Text12'],
	'aaaa'=> 'Yes'

);

$pdf = new FPDM('check1.pdf');
$pdf->Load($fields, false); // second parameter: false if field values are in ISO-8859-1, true if UTF-8
$pdf->Merge();
$pdf->Output();
 
    ob_end_flush(); 
 `}`
