### ISSUE TITLE
Turkish capital letters not working

### ISSUE THREAD

**Issue by aren3k** [mikehaertl/php-pdftk#329] opened 2024-05-07 12:27 UTC
Hi,

I'm having some issues with printing Turkish capital letters in a form field. When using normal font size everything is ok.
I have tried many fonts in the meantime, all the same issue.

Was wondering if this really is a font related issue?

$pdf->fillForm($pdfData)
    ->needAppearances()
    ->saveAs($destinationFilePath);

The result I get for POLARİS ELEKTRONİK:
![image](https://github.com/mikehaertl/php-pdftk/assets/125046880/0c298848-1293-45e5-a961-d9025c03bfa8)

**Comment by mikehaertl** [comment] 2024-05-07 12:50
I'm sorry but this kind of problems is out of scope of this library. It's usually *always* caused by some font problems (which can be a pain to get right sometimes). Unfortunately there's nothing we can do about it here.

**Closed by mikehaertl** 2024-05-07 12:50 UTC

**Comment by aren3k** [comment] 2024-05-07 12:53
@mikehaertl Thanks for your response, I'll look further towards figuring out a correct font. Have a great day!
