### ISSUE TITLE
Adding a signature to PDF

### ISSUE THREAD

**Issue by edgaraafelix** [mikehaertl/php-pdftk#186] opened 2020-03-24 14:33 UTC
Is it possible to fill a signature element on a given PDF?

Not sure if I see support for this on php-pdftk.

**Comment by mikehaertl** [comment] 2020-03-24 15:53
Not sure what you mean. Can you explain?

**Comment by mikehaertl** [comment] 2020-04-01 12:55
Closing this as there was no further feedback.

**Closed by mikehaertl** 2020-04-01 12:55 UTC

**Comment by edgaraafelix** [comment] 2021-02-23 12:12
@mikehaertl

I got pretty busy at the same time I created this issue/discussion.

As I am getting back to this subject, what I meant was if it is possible to fill in a signature element using your wrapper as in passing an image, let's say a .PNG, to the signature object.

I'm referring to the following field type:

<img width="797" alt="Signature1" src="https://user-images.githubusercontent.com/3910766/108841874-5551be80-75d0-11eb-9e6c-1a250d98c324.png">

**Comment by mikehaertl** [comment] 2021-02-23 12:28
@edgaraafelix I may be wrong but I don't think `pdftk` can do this. If it can and you could show me the command line string, we can add such a feature.

**Comment by sdevore** [comment] 2021-02-23 17:10
the only way i have gotten this to work is to basically do this https://gist.github.com/chrpinedo/a2a2af757e96aec0d6f69d707629a01a

**Comment by edgaraafelix** [comment] 2021-02-23 17:22
@sdevore I have seen that solution. The thing is that I have multiple PDF files with multiple signature locations as well, with stamps I would have to put it in the right location (x an y positions) on a blank PDF and then stamp it to the original PDF.

**Comment by edgaraafelix** [comment] 2021-02-23 19:24
> @edgaraafelix I may be wrong but I don't think `pdftk` can do this. If it can and you could show me the command line string, we can add such a feature.

@mikehaertl I do think the same. I'm still looking into it and actually found [rammie/pdfjinja](https://github.com/rammie/pdfjinja/), it's written in python and additionally to filling form fields, it basically pastes images into a signature object.

I might use it only to "paste" the image into the signature object but it would be cool to find a way to implement something similar for `php-pdftk`.

**Comment by SantinoPetrovic** [comment] 2022-02-04 07:17
I had to use mpdf lib for this part. The problem is though it cannot locate the image field at all (so I had to define x and y locations for each image field). If it were possible to find a way to extract x and y locations from the data fields, then the problem would be solved. I don't think this feature is on pdftk or this lib, right?
